package main

import (
	"bytes"
	"flag"
	"os"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var update = flag.Bool("update", false, "rewrite golden files")

const (
	usageDoc  = "../../README.md"
	beginMark = "<!-- BEGIN REFERENCE (generated by `make docs`, do not edit) -->\n"
	endMark   = "<!-- END REFERENCE -->\n"
)

// TestUsageDoc is the CLI docs drift guard: the Reference section of
// README.md must match the cobra tree. `make docs` rewrites it.
func TestUsageDoc(t *testing.T) {
	raw, err := os.ReadFile(usageDoc)
	require.NoError(t, err)

	doc := string(raw)
	begin := strings.Index(doc, beginMark)
	end := strings.Index(doc, endMark)
	require.True(t, begin >= 0 && end > begin, "README.md needs the reference markers")

	want := doc[:begin+len(beginMark)] + reference() + doc[end:]

	if *update {
		require.NoError(t, os.WriteFile(usageDoc, []byte(want), 0o600))

		return
	}

	assert.Equal(t, want, doc, "README.md is stale: run `make docs`")
}

func TestReferenceCoversEveryCommand(t *testing.T) {
	ref := reference()

	for _, c := range newRoot(testDeps()).Commands() {
		if c.Hidden {
			continue
		}

		assert.Contains(t, ref, "### sandboxed_agent "+c.Name()+"\n")
	}
}

func testDeps() deps {
	return deps{stdin: strings.NewReader(""), stdout: &bytes.Buffer{}, stderr: &bytes.Buffer{}, cwd: cwd, actions: defaultActions()}
}

// reference renders every visible command's help, root first.
func reference() string {
	var b strings.Builder

	root := newRoot(testDeps())
	writeHelp(&b, "sandboxed_agent", root)

	for _, c := range root.Commands() {
		if c.Hidden || c.Name() == "help" {
			continue
		}

		writeHelp(&b, "sandboxed_agent "+c.Name(), c)
	}

	return b.String()
}

func writeHelp(b *strings.Builder, title string, c *cobra.Command) {
	var out bytes.Buffer
	c.SetOut(&out)
	if err := c.Help(); err != nil {
		panic(err)
	}

	b.WriteString("\n### " + title + "\n\n```text\n" + out.String() + "```\n")
}
